# Generated by Django 5.2.17 on 2026-09-15 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestaurantSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gst_rate_basis_points", models.PositiveIntegerField(default=500)),
                ("packing_charge_paise", models.PositiveBigIntegerField(default=0)),
                ("delivery_fee_paise", models.PositiveBigIntegerField(default=0)),
                (
                    "free_delivery_threshold_paise",
                    models.PositiveBigIntegerField(default=0),
                ),
            ],
            options={
                "verbose_name": "Restaurant settings",
                "verbose_name_plural": "Restaurant settings",
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subtotal_paise", models.PositiveBigIntegerField()),
                ("discount_total_paise", models.PositiveBigIntegerField()),
                ("packing_charge_paise", models.PositiveBigIntegerField()),
                ("delivery_fee_paise", models.PositiveBigIntegerField()),
                ("taxable_amount_paise", models.PositiveBigIntegerField()),
                ("gst_paise", models.PositiveBigIntegerField()),
                ("total_paise", models.PositiveBigIntegerField()),
                ("breakdown", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bill",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
