# Generated by Django 5.2.17 on 2026-09-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed amount"),
                            ("percentage", "Percentage"),
                        ],
                        max_length=20,
                    ),
                ),
                ("minimum_order_paise", models.PositiveBigIntegerField(default=0)),
                ("discount_value", models.PositiveBigIntegerField()),
                (
                    "maximum_discount_paise",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("priority", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "stacking_policy",
                    models.CharField(
                        choices=[
                            ("exclusive", "Exclusive"),
                            ("stackable", "Stackable"),
                        ],
                        default="exclusive",
                        max_length=20,
                    ),
                ),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-priority", "id"],
            },
        ),
    ]
